### ISSUE TITLE
Unused code in server.js

### ISSUE THREAD

**Issue by justincastilla** [margarh1/project-1-bucketlist#1]
@margarh1 @Sol1323 
Found a line of unused code @
https://github.com/margarh1/project-1-bucketlist/blob/margaretdevelop/server.js#L94

Please consider removing or altering code.

Thanks,
Jusitn

**Comment by justincastilla** [comment]
Please hurry up.

**Comment by margarh1** [comment]
Alright, I'm on it

**Comment by margarh1** [comment]
@justincastilla 

Fixes issue #1
- removed commented code

**Comment by justincastilla** [comment]
Thanks, u da bes!
